name: Example workflow

on: [push]

jobs:
  check:
    name: A job to say hello

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run example action step
        uses: ./
        with:
          name: "John Doe"
